name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.10.0
    - name: Build binaries
      run: docker build --cache-from type=registry,ref=rsdate/rpkg:buildcache --cache-to type=registry,ref=rsdate/rpkg:buildcache --output=. .
    - name: Test out binaries
      run: tar -xzf ./rpkg.tar.gz && ./out/linux/rpkg_linux_amd64 --help
