name: Docker Image CI

on:
  push:
    branches: [ "main", "weekly_build" ]
  pull_request:
    branches: [ "main", "weekly_build" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.10.0
    - name: Set up a gha cache-supported Docker driver
      run: docker buildx create 
        --name rpkg-builder 
        --driver=docker-container 
        --driver-opt=default-load=true
    - name: Build binaries
      run: docker buildx build 
        --builder=rpkg-builder 
        --cache-from type=gha 
        --cache-to type=gha,mode=max 
        --file docker/export/Dockerfile 
        --output=. .
    - name: Test out binaries
      run: tar -xzvf ./app/rpkg.tar.gz && ./app/out/linux/rpkg_linux_amd64 --help
