name: Docker Image CI

on:
  push:
    branches: [ "main", "weekly_build" ]
  pull_request:
    branches: [ "main", "weekly_build" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.10.0
    - name: Build binaries
      run: docker build --cache-from type=registry,ref=rsdate/rpkg:buildcache --cache-to type=registry,ref=rsdate/rpkg:buildcache --output=. .
    - name: Test out binaries
      run: tar -xzf ./rpkg.tar.gz && ./out/linux/rpkg_linux_amd64 --help
